server:
  ingress:
    enabled: true
    hostname: argocd-server.argocd
  extraArgs:
    - --insecure
  additionalApplications:
    - name: service-catalog
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/prabhav007/service-catalog-poc.git
        targetRevision: HEAD
        path: argocd
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true